environment: development
azureTenantId:
environmentCode:
tenantId:
name: ffc-customer-registry-api
namespace: ffc-cr
workstream: ffc-cr
image: ffc-customer-registry-api
mockServerEnabled: true

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-customer-registry-api-config-map

containerSecret:
  name: ffc-customer-registry-api-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

ingress:
  class: nginx
  endpoint: ffc-customer-registry-api
  server: example.com

adGroups:
  admin:

dataSources:
  ruralPaymentAgencyLandApiUrl: not-real
  ruralPaymentPortalApiUrl: not-real
  ruralPaymentPortalEmail: not-real
  ruralPaymentPortalPassword: not-real
