type BusinessApplicationStatus {
  id: ID
  open: String
  status: String
  type: String
  sector: String
  year: String
  frn: String
  office: String
}

type BusinessApplicationClaims {
  schemeYear: String
  type: String
  status: String
  lastMovement: String
}

type BusinessApplication {
  applicationStatus: BusinessApplicationStatus
  csClaims: BusinessApplicationClaims
}
