type CPHCoordinate {
  x: Int
  y: Int
}

type CPHInfo {
  parish: String
  startDate: String
  expiryDate: Int
  species: [String]
  coordinate: CPHCoordinate
}

type CPH {
  number: String
  parcelNumbers: [String]
  info: CPHInfo
}
