type LandCover {
  id: ID!
}

type LandParcel {
  id: ID!
  area: Float
  landCovers: [LandLandCover]
}

type LandSummary {
  date: Date
  numberOfParcels: Numeric
  totalArea: Numeric
  mapImageData: Image
  permanentGrassland: Numeric
}

type Land {
  parcels: LandParcels
  summary: LandSummary
}

extend type Query {
  land(businessId: ID!): Land
}
