type LandArea {
  code: Int
  name: String
  area: Int
}

type LandCover {
  id: ID!
  areas: [LandArea]
}

type LandGeometry {
  type: String
  coordinates: [[String]]
}

type LandParcelFeature {
  id: ID!
  area: LandArea
  geometry: LandGeometry
}

type LandParcel {
  id: ID!
  area: Float
  sheetId: String
  parcelId: String
  features: String
}

type LandSummary {
  date: Date
  numberOfParcels: Numeric
  totalArea: Numeric
  mapImageData: Image
  permanentGrassland: Numeric
}

type Land {
  summary: LandSummary
  parcels: [LandParcel]
  covers: [LandCover]
}

extend type Query {
  land(businessId: ID!): Land
}
