type Customer {
    firstName: String
    surname: String
    memorableDate: String
    memorableLocation: String
    memorableEvent: String
}

input CustomerUpdate {
    customerReferenceNumber: Int!
    memorableDate: String
    memorableLocation: String
    memorableEvent: String
}

extend type Query {
    Customer(customerReferenceNumber: Int!): Customer
}

extend type Mutation {
    Customer(customer: CustomerUpdate): Customer
}
