type PersonName {
  title: String
  otherTitle: String
  first: String
  middle: String
  last: String
}

type PersonStatus {
  locked: Boolean
  confirmed: Boolean
  deactivated: Boolean
}

type Person {
  id: ID!
  customerReferenceNumber: String
  name: PersonName
  dateOfBirth: Date
  phone: Phone
  email: Email
  status: PersonStatus
  address: Address
}

extend type Query {
  person(id: ID!): Person
}
