parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: deployConfigOnly
    displayName: "Deploy App Config"
    type: boolean
    default: false
pr:
  branches:
    include:
      - main
      - master
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*
  drafts: false

trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    exclude:
      - test-output/*
      - bin/*
      - obj/*

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: main

extends:
  template: /pipelines/common-app-build.yaml@DEFRA-ADPPipelineCommon
  parameters:
    serviceName: "fcp-data-access-layer-api"
    deployFromFeature: ${{ parameters.deployFromFeature }}
    deployConfigOnly: ${{ parameters.deployConfigOnly }}
    appBuildConfig:
      appFrameworkType: "nodejs"
      projectPath: "./package.json"
      manifestPath: "./package.json"
      imageRepoName: "fcp-data-access-layer-api"
    appTestConfig:
      testFilePath: "./docker-compose.test.yaml"
      snykTestFilePath: "./docker-compose.snyk.yaml"
    appDeployConfig:
      filepath: "./appConfig"
      filetype: "yaml"
      variableGroups:
        - fcp-data-access-layer-api-<environment>
      variables:
        - fcp-data-access-layer-api-APPINSIGHTS-CONNECTIONSTRING
        - fcp-data-access-layer-api-RURAL-PAYMENTS-PORTAL-PASSWORD
        - fcp-data-access-layer-api-API-TENANT-ID
        - fcp-data-access-layer-api-ADMIN-AD-GROUP-ID
