{{- include "ffc-helm-library.container-config-map" (list . "ffc-customer-registry-api.config-map") -}}
{{- define "ffc-customer-registry-api.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  MOCK_LEVEL: {{ quote .Values.mock_level }}
{{- end -}}
