{{- include "ffc-helm-library.container-config-map" (list . "ffc-customer-registry-api.config-map") -}}
{{- define "ffc-customer-registry-api.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  ENABLE_MOCK_SERVER: {{ quote .Values.mockServerEnabled }}
  RURAL_PAYMENTS_PORTAL_API_URL: {{ quote .Values.dataSources.ruralPaymentPortalApiUrl }}
  RURAL_PAYMENTS_AGENCY_LAND_API_URL: {{ quote .Values.dataSources.ruralPaymentAgencyLandApiUrl }}
{{- end -}}