{{- include "ffc-helm-library.container-secret" (list . "ffc-customer-registry-api.container-secret") -}}
{{- define "ffc-customer-registry-api.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  ADMIN_AD_GROUP_ID: {{ quote .Values.adGroups.admin }}
  RURAL_PAYMENTS_PORTAL_EMAIL: {{ quote .Values.dataSources.ruralPaymentPortalEmail }}
  RURAL_PAYMENTS_PORTAL_PASSWORD: {{ quote .Values.dataSources.ruralPaymentPortalPassword }}
{{- end -}}
