input UpdateCustomerAuthenticationQuestionsInput {
  referenceNumber: Int!
  memorableDate: String
  memorableEvent: String
  memorablePlace: String
}

extend type Mutation {
  updateCustomerAuthenticationQuestions(
    input: UpdateCustomerAuthenticationQuestionsInput!
  ): CustomerAuthenticationQuestions
}
